### ISSUE TITLE
Enter button HEX code

### ISSUE THREAD

**Issue by JSa1987** [devjklein/yamaha-rx-v363-ir-codes#3]
Hello,

This is not a issue, but a question. Do you have the Hex code for the "Enter" button?
The button that would be in the middle between the Up/Down/Left/Right arrow buttons.

**Comment by devjklein** [comment]
Apologies, I am not using this particular receiver anymore, so I do not have the remote on hand. However, I have several PDFs attached to this GitHub that contain tables of codes I used to construct my list, many of which are common between Yamaha receivers.

[Yamaha Extended IR codes for RX-V685, RX-A780 - RX-A3080 and CX-A5200](https://github.com/devjklein/yamaha-rx-v363-ir-codes/blob/main/Extended_IR_Codes_RX-V685RX-A780-RX-A3080CX-A5200_6.pdf)

[Yamaha Standard IR codes for RX-V685, RX-A780 - RX-A3080 and CX-A5200](https://github.com/devjklein/yamaha-rx-v363-ir-codes/blob/main/Standard_IR_Codes_RX-V685RX-A780-RX-A3080CX-A5200_4.pdf)

[Yamaha Standard & Extended IR codes for XDA-QS5400RK and XDA-AMP5400RK](https://github.com/devjklein/yamaha-rx-v363-ir-codes/blob/main/XDA-QS5400_XDA-AMP5400_IR_Commands.pdf)

**Comment by devjklein** [comment]
Closing as not planned as I do not have resources to test.
